# Generated by Django 2.1.7 on 2019-02-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190214_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='info',
            new_name='body',
        ),
    ]
